authors = ["William Herrera <wherrera@alahonua.com>"]
name = "ToyECDSA"
uuid = "a867f1d8-37c0-5396-a34b-6f6aa200a1c2"
version = "0.0.1"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1"
